
package defaultnamespace;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Calculator", targetNamespace = "http://DefaultNamespace")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Calculator {


    /**
     * 
     * @param secondNumber
     * @param firstNumber
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "addReturn", targetNamespace = "http://DefaultNamespace")
    @RequestWrapper(localName = "add", targetNamespace = "http://DefaultNamespace", className = "defaultnamespace.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://DefaultNamespace", className = "defaultnamespace.AddResponse")
    public int add(
        @WebParam(name = "firstNumber", targetNamespace = "http://DefaultNamespace")
        int firstNumber,
        @WebParam(name = "secondNumber", targetNamespace = "http://DefaultNamespace")
        int secondNumber);

}
